name = "Rambo"
uuid = "f6c090b2-c93c-11e9-2096-875511698ca0"
authors = ["Logan Morrison"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
